# Generated by Django 4.2.9 on 2024-01-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='UserID',
            new_name='CustomerID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='UserID',
            new_name='CustomerID',
        ),
    ]
