# Generated by Django 4.2.9 on 2024-01-09 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_customer_first_name_customer_last_name_and_more'),
        ('listings', '0002_rename_userid_bid_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='OwnerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bidding_starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bidding',
            field=models.BooleanField(default=True),
        ),
    ]
