# Generated by Django 4.2.9 on 2024-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='medium',
            field=models.CharField(choices=[('cd', 'CD'), ('vinyl', 'Vinyl'), ('casette', 'Casette'), ('other', 'Other')], default=('cd', 'CD'), max_length=10),
        ),
    ]
