# Generated by Django 4.2.9 on 2024-01-14 22:25

from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_artist_remove_listing_artist_listing_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ArtistID',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip hop', 'Hip Hop'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('country', 'Country'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('folk', 'Folk'), ('r&b', 'R&B'), ('reggae', 'Reggae'), ('punk', 'Punk'), ('metal', 'Metal'), ('indie', 'Indie'), ('rap', 'Rap'), ('soul', 'Soul'), ('funk', 'Funk'), ('dance', 'Dance'), ('ambient', 'Ambient')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria'), ('argentina', 'Argentina'), ('australia', 'Australia'), ('austria', 'Austria'), ('bangladesh', 'Bangladesh'), ('brazil', 'Brazil'), ('canada', 'Canada'), ('china', 'China'), ('colombia', 'Colombia'), ('egypt', 'Egypt'), ('france', 'France'), ('germany', 'Germany'), ('india', 'India'), ('indonesia', 'Indonesia'), ('iran', 'Iran'), ('iraq', 'Iraq'), ('italy', 'Italy'), ('japan', 'Japan'), ('mexico', 'Mexico'), ('netherlands', 'Netherlands'), ('nigeria', 'Nigeria'), ('pakistan', 'Pakistan'), ('peru', 'Peru'), ('philippines', 'Philippines'), ('poland', 'Poland'), ('russia', 'Russia'), ('saudi arabia', 'Saudi Arabia'), ('south africa', 'South Africa'), ('south korea', 'South Korea'), ('spain', 'Spain'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('thailand', 'Thailand'), ('turkey', 'Turkey'), ('ukraine', 'Ukraine'), ('united arab emirates', 'United Arab Emirates'), ('united kingdom', 'United Kingdom'), ('united states', 'United States'), ('venezuela', 'Venezuela'), ('vietnam', 'Vietnam'), ('yemen', 'Yemen')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=listings.models.directory_path)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.artist')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.record'),
        ),
    ]
