# Generated by Django 4.2.9 on 2024-01-20 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0013_alter_listing_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sellerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
