# Generated by Django 4.2.9 on 2024-01-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_remove_bid_customerid_remove_order_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
