# Generated by Django 4.2.9 on 2024-01-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
