# Generated by Django 4.2.9 on 2024-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_screen_name_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='screen_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
