# Generated by Django 4.2.9 on 2024-01-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_screen_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, choices=[('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria'), ('argentina', 'Argentina'), ('australia', 'Australia'), ('austria', 'Austria'), ('bangladesh', 'Bangladesh'), ('brazil', 'Brazil'), ('canada', 'Canada'), ('china', 'China'), ('colombia', 'Colombia'), ('egypt', 'Egypt'), ('france', 'France'), ('germany', 'Germany'), ('india', 'India'), ('indonesia', 'Indonesia'), ('iran', 'Iran'), ('iraq', 'Iraq'), ('italy', 'Italy'), ('japan', 'Japan'), ('mexico', 'Mexico'), ('netherlands', 'Netherlands'), ('nigeria', 'Nigeria'), ('pakistan', 'Pakistan'), ('peru', 'Peru'), ('philippines', 'Philippines'), ('poland', 'Poland'), ('russia', 'Russia'), ('saudi arabia', 'Saudi Arabia'), ('south africa', 'South Africa'), ('south korea', 'South Korea'), ('spain', 'Spain'), ('sweden', 'Sweden'), ('switzerland', 'Switzerland'), ('thailand', 'Thailand'), ('turkey', 'Turkey'), ('ukraine', 'Ukraine'), ('united arab emirates', 'United Arab Emirates'), ('united kingdom', 'United Kingdom'), ('united states', 'United States'), ('venezuela', 'Venezuela'), ('vietnam', 'Vietnam'), ('yemen', 'Yemen')], max_length=100, null=True),
        ),
    ]
